#!/usr/bin/env bash
# Run PR Agent review locally against branch diff
#
# Mirrors the CI PR Agent review (ai-review.yml) for local pre-push feedback.
# Reuses .pr_agent.toml generated by build-pr-agent-config.sh.
#
# Usage:
#   scripts/local-pr-review.sh                            # Branch diff vs main
#   scripts/local-pr-review.sh --staged                   # Staged changes only
#   scripts/local-pr-review.sh --files backend/app/api/   # File-scoped review
#   scripts/local-pr-review.sh --output review.json       # Write output to file

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

PR_AGENT_IMAGE="codiumai/pr-agent:latest"

# ─── Argument parsing ─────────────────────────────────────────────────────────

FILES_PATH=""
OUTPUT_FILE=""


usage() {
  cat <<'EOF'
Usage: scripts/local-pr-review.sh [OPTIONS]

Run PR Agent review against the current branch's open GitHub PR.
Reuses the same .pr_agent.toml config as CI (build-pr-agent-config.sh).
Requires the branch to have an open PR on GitHub.

Options:
  --files <path>           Scope review focus to specific file(s)
  --output <file>          Write review output to file in addition to stdout
  --pr-url <url>           Use this GitHub PR URL instead of auto-detecting
  --help                   Show this help message

Environment (required):
  GITHUB_TOKEN             GitHub token — used for PR API access

Environment (LLM — one required):
  OPENAI_API_KEY           OpenAI-compatible key (use 'lm-studio' for LM Studio)

  OPENAI_BASE_URL          API base URL (e.g. http://localhost:1234/v1 for LM Studio)
  OPENAI_MODEL             Model name (e.g. google/gemma-4-31b)

  For LM Studio:
    export OPENAI_API_KEY=lm-studio
    export OPENAI_BASE_URL=http://localhost:1234/v1
    export OPENAI_MODEL=google/gemma-4-31b

  For GitHub Copilot (uses GITHUB_TOKEN as LLM key):
    export OPENAI_BASE_URL=https://api.githubcopilot.com

Examples:
  # Review the current branch's open PR
  scripts/local-pr-review.sh

  # Focus review on a specific file
  scripts/local-pr-review.sh --files backend/app/api/items.py

  # Use an explicit PR URL
  scripts/local-pr-review.sh --pr-url https://github.com/org/repo/pull/42

  # Save output to file
  scripts/local-pr-review.sh --output review.json

Exit codes:
  0  No blocking findings
  1  Blocking findings detected ("Request Changes") or error
EOF
}

PR_URL_OVERRIDE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --files)
      if [[ $# -lt 2 ]]; then
        echo "❌ --files requires a path argument" >&2
        exit 1
      fi
      FILES_PATH="$2"
      shift 2
      ;;
    --output)
      if [[ $# -lt 2 ]]; then
        echo "❌ --output requires a file argument" >&2
        exit 1
      fi
      OUTPUT_FILE="$2"
      shift 2
      ;;
    --pr-url)
      if [[ $# -lt 2 ]]; then
        echo "❌ --pr-url requires a URL argument" >&2
        exit 1
      fi
      PR_URL_OVERRIDE="$2"
      shift 2
      ;;
    --help | -h)
      usage
      exit 0
      ;;
    *)
      echo "❌ Unknown flag: '$1'" >&2
      echo "Run with --help for usage." >&2
      exit 1
      ;;
  esac
done

# ─── Prerequisite checks ──────────────────────────────────────────────────────

echo "▶ Checking prerequisites..."

# Docker availability
if ! command -v docker &>/dev/null; then
  cat >&2 <<'EOF'
❌ Docker not found.
   Install Docker Desktop: https://docs.docker.com/get-docker/
   Then start Docker Desktop and retry.
EOF
  exit 1
fi

if ! docker info &>/dev/null 2>&1; then
  cat >&2 <<'EOF'
❌ Docker daemon is not running.
   Start Docker Desktop and retry.
EOF
  exit 1
fi

# GITHUB_TOKEN — always required for GitHub PR API access
if [[ -z "${GITHUB_TOKEN:-}" ]]; then
  cat >&2 <<'EOF'
❌ GITHUB_TOKEN is required for GitHub PR API access.
   export GITHUB_TOKEN=<your-github-token>
EOF
  exit 1
fi

# OPENAI_API_KEY — required for LLM access; falls back to GITHUB_TOKEN (Copilot mode)
if [[ -z "${OPENAI_API_KEY:-}" ]]; then
  # Use GITHUB_TOKEN as the LLM key (GitHub Copilot provider)
  export OPENAI_API_KEY="${GITHUB_TOKEN}"
  if [[ -z "${OPENAI_BASE_URL:-}" && -z "${OPENAI_API_BASE:-}" ]]; then
    export OPENAI_BASE_URL="https://api.githubcopilot.com"
  fi
fi

# Git repository check
if ! git -C "$REPO_ROOT" rev-parse --is-inside-work-tree &>/dev/null 2>&1; then
  echo "❌ Not inside a git repository." >&2
  exit 1
fi

echo "✅ Prerequisites OK"

# ─── Config generation ────────────────────────────────────────────────────────

echo "▶ Generating PR Agent config from guidelines..."
bash "$REPO_ROOT/scripts/build-pr-agent-config.sh"

if [[ ! -f "$REPO_ROOT/.pr_agent.toml" ]]; then
  echo "❌ Config generation failed: .pr_agent.toml not found" >&2
  exit 1
fi

echo "✅ Config generated at .pr_agent.toml"

# Normalise: accept OPENAI_BASE_URL (LiteLLM/OpenAI SDK) as an alias for
# OPENAI_API_BASE (PR Agent) so that callers can use either name.
if [[ -z "${OPENAI_API_BASE:-}" && -n "${OPENAI_BASE_URL:-}" ]]; then
  export OPENAI_API_BASE="$OPENAI_BASE_URL"
fi

# Apply local LLM overrides directly into the [config] section of .pr_agent.toml
# so they take effect without creating duplicate TOML sections.
if [[ -n "${OPENAI_MODEL:-}" || -n "${OPENAI_API_BASE:-}" ]]; then
  python3 - "$REPO_ROOT/.pr_agent.toml" <<PYEOF
import sys, re

path = sys.argv[1]
text = open(path).read()

# Replace model value in [config] section if OPENAI_MODEL is set
model_override = "${OPENAI_MODEL:-}"
if model_override:
    # For custom OpenAI-compatible endpoints (e.g. LM Studio), LiteLLM requires
    # the model to be prefixed with "openai/" to route via the OpenAI client with
    # the custom OPENAI_API_BASE, rather than forwarding to a cloud provider.
    api_base_override = "${OPENAI_API_BASE:-}"
    if api_base_override and not model_override.startswith("openai/"):
        model_override = "openai/" + model_override
    text = re.sub(r'(?m)^(model\s*=\s*).*$', f'model = "{model_override}"', text, count=1)

# When using a local LLM server, set custom_model_max_tokens so PR Agent knows
# the context window size for unknown model names (e.g. google/gemma-4-31b).
# Do NOT lower max_model_tokens globally — it would also cap the fallback model.
api_base_override = "${OPENAI_API_BASE:-}"
if api_base_override and 'custom_model_max_tokens' not in text:
    text = re.sub(r'(?m)^(\[config\])', r'\1\ncustom_model_max_tokens = 4096', text, count=1)

# Add [ignore] glob section to skip doc/config files and reduce the diff to
# only code files — shrinks the prompt to fit local model context windows.
if api_base_override and '[ignore]' not in text:
    text += '\n[ignore]\nglob = ["**/*.md", "**/*.yaml", "**/*.yml", "**/*.toml", "**/*.sh"]\n'

open(path, 'w').write(text)
PYEOF
  echo "  Config overrides applied (model=${OPENAI_MODEL:-default}, local LLM=${OPENAI_API_BASE:+yes})"
fi

# ─── PR URL detection ─────────────────────────────────────────────────────────

echo "▶ Detecting PR URL..."

_pr_url="${PR_URL_OVERRIDE:-}"

if [[ -z "$_pr_url" ]]; then
  if ! command -v gh &>/dev/null; then
    cat >&2 <<'EOF'
❌ Cannot auto-detect PR URL: 'gh' (GitHub CLI) not found.
   Install: https://cli.github.com/
   Or pass: --pr-url <github-pr-url>
EOF
    exit 1
  fi

  _pr_url=$(gh pr view --json url --jq '.url' 2>/dev/null || true)

  if [[ -z "$_pr_url" ]]; then
    cat >&2 <<'EOF'
❌ No open PR found for the current branch.
   Push your branch and open a PR first, then retry.
   Or pass: --pr-url <github-pr-url>
EOF
    exit 1
  fi
fi

echo "  PR: $_pr_url"

# ─── PR Agent execution ───────────────────────────────────────────────────────

echo "▶ Running PR Agent (${PR_AGENT_IMAGE})..."

# Resolve and rewrite API base URL: OPENAI_BASE_URL preferred over OPENAI_API_BASE.
# Rewrite localhost → host.docker.internal so the container can reach LM Studio.
_api_base=""
if [[ -n "${OPENAI_BASE_URL:-}" ]]; then
  _api_base="$OPENAI_BASE_URL"
elif [[ -n "${OPENAI_API_BASE:-}" ]]; then
  _api_base="$OPENAI_API_BASE"
fi
if [[ -n "$_api_base" ]]; then
  _api_base="${_api_base/localhost/host.docker.internal}"
  _api_base="${_api_base/127.0.0.1/host.docker.internal}"
  export OPENAI_API_BASE="$_api_base"
fi

# PR_AGENT_CONFIG: pass the (already-modified) .pr_agent.toml as an env string,
# matching the same mechanism used in CI.
export PR_AGENT_CONFIG
PR_AGENT_CONFIG=$(cat "$REPO_ROOT/.pr_agent.toml")

# Docker env args — secrets are passthrough (never embedded in command args).
# PR Agent reads GitHub token via dynaconf key GITHUB__USER_TOKEN (double underscore).
export GITHUB__USER_TOKEN="${GITHUB_TOKEN}"
_docker_env_args=("-e" "GITHUB__USER_TOKEN" "-e" "OPENAI_API_KEY" "-e" "PR_AGENT_CONFIG")
if [[ -n "${OPENAI_API_BASE:-}" ]]; then
  _docker_env_args+=("-e" "OPENAI_API_BASE")
fi

# File-scoped review: add as extra instructions to the reviewer.
_extra_pr_agent_args=()
if [[ -n "$FILES_PATH" ]]; then
  _extra_pr_agent_args+=(
    "--pr_reviewer.extra_instructions=Focus the review only on changes in: ${FILES_PATH}"
  )
fi

# Mount the generated .pr_agent.toml as .secrets.toml inside the container so
# the custom_merge_loader picks it up (it loads file-based TOML only, not the
# PR_AGENT_CONFIG env var string).  This ensures extra_instructions and all
# reviewer config from the guidelines reach the model.
_docker_volume_args=(
  "-v" "$REPO_ROOT/.pr_agent.toml:/app/pr_agent/settings/.secrets.toml:ro"
)

# When using a local LLM server, override model and custom_model_max_tokens via
# direct Dynaconf env vars (CONFIG__KEY).  These are processed by the env_loader
# which runs after file loaders, so they take the highest precedence.
# custom_model_max_tokens informs PR Agent of the context window for unknown
# model names (e.g. google/gemma-4-31b from LM Studio).
if [[ -n "${OPENAI_API_BASE:-}" ]]; then
  # Prefix model with "openai/" so LiteLLM routes via OpenAI-compatible client
  # to the custom OPENAI_API_BASE rather than to a cloud provider directly.
  _model_for_litellm="${OPENAI_MODEL}"
  if [[ "${_model_for_litellm}" != openai/* ]]; then
    _model_for_litellm="openai/${_model_for_litellm}"
  fi
  _docker_env_args+=("-e" "CONFIG__MODEL=${_model_for_litellm}")
  _docker_env_args+=("-e" "CONFIG__CUSTOM_MODEL_MAX_TOKENS=4096")
fi

# Run PR Agent — API keys passed via env only; never appear in command args.
_review_exit=0
_review_output=$(
  docker run --rm \
    --platform linux/amd64 \
    "${_docker_env_args[@]}" \
    "${_docker_volume_args[@]}" \
    "${PR_AGENT_IMAGE}" \
    --pr_url "$_pr_url" \
    "${_extra_pr_agent_args[@]+"${_extra_pr_agent_args[@]}"}" \
    review \
    2>&1
) || _review_exit=$?

if [[ $_review_exit -ne 0 ]]; then
  echo "$_review_output"
  echo "" >&2
  echo "❌ PR Agent failed (exit ${_review_exit})" >&2
  exit 1
fi


echo "$_review_output"

if [[ -n "$OUTPUT_FILE" ]]; then
  echo "$_review_output" > "$OUTPUT_FILE"
  echo "✅ Output written to $OUTPUT_FILE"
fi

# ─── Fetch review result from GitHub ─────────────────────────────────────────
# PR Agent posts the review as a regular PR comment (not a GitHub PR review with
# a verdict state).  The comment body starts with "## PR Reviewer Guide".
# When running locally with the user's own token the comment is authored by the
# user account, so we match by body content, not by author type.

_review_body=""
if command -v gh &>/dev/null; then
  echo ""
  echo "▶ Fetching review result from GitHub PR..."

  # Wait briefly for GitHub to register the posted comment (eventual consistency)
  sleep 3

  _pr_number=$(basename "$_pr_url")
  _review_body=$(gh api "repos/{owner}/{repo}/issues/${_pr_number}/comments" \
    --jq '[.[] | select(.body | test("^## PR Reviewer Guide"))] | last | .body' \
    2>/dev/null || true)

  if [[ -z "$_review_body" || "$_review_body" == "null" ]]; then
    echo "⚠ Could not retrieve review comment from GitHub (may still be processing)"
  else
    echo ""
    echo "──────────────────────────────────────────────────────────────────"
    # Print full review; limit to 200 lines to keep terminal readable
    echo "$_review_body" | head -200
    echo "──────────────────────────────────────────────────────────────────"
  fi
fi

# ─── Exit code ────────────────────────────────────────────────────────────────
# PR Agent signals blocking findings via:
#   • "Major issues detected" in the summary table (no "No " prefix)
#   • 🔴 emoji — marks critical / must-fix feedback items

if echo "$_review_body" | grep -qE "Major issues detected|🔴"; then
  echo ""
  echo "❌ Review complete: blocking findings detected — fix before pushing"
  exit 1
else
  echo ""
  echo "✅ Review complete: no blocking findings detected"
  exit 0
fi
